config/routes.rb
Rails.application.routes.draw do

  root 'expenses#index'
  resources :expenses
  get 'about' => 'static_pages#about'
  get 'new_record' => 'static_pages#new_record'
end

app/models/expense.rb
class Expense < ActiveRecord::Base
     validates :description, :amount, :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
    def index
        @expenses = Expense.all
        
    end
    
  
    def create
        @expenses = Expense.create(expense_params)
        if @expenses.valid?
            flash[:success] = "Your expense is recorded!"
        else
            flash[:alert] = "Woops! Looks like there has been an error!"
        end
        redirect_to root_path
    end
      
    def edit
        @expenses = Expense.find(params[:id])
   
    end
    
    def update
        @expense = Expense.find(params[:id])
        if@expense.update(expense_params)
            flash[:success] = "The details has been updated!"
            redirect_to root_path 
        else
            flash[:alert] = "Woops! Looks like there has been an error!"
            redirect_to edit_expense_path(params[:id])
        end
        
    end
    
    def destroy
        @expense = Expense.find(params[:id])
        @expense.destroy
        flash[:success] = "Successfully deleted!"
        redirect_to root_path
        
    end
    
    private
    
        def expense_params
             
            params.require(:expense).permit(:description, :amount, :date)
        end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def new_record
    end
    
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/expenses/edit.html.erb
<h1>Edit</h1>

<%= simple_form_for @expenses do |f| %>
<%= f.input :description %>
  <%= f.input :amount %>
  <%= f.input :date %>
  <%= f.submit 'DONE', class: 'btn btn-primary' %>
<% end %>

app/views/expenses/index.html.erb
<div class="info"><h1>Online Wallet</h1>
<p>Record your daily expenses</p>
<p>Never forget wher you spent your money</p>
</div>
<br>
<div  class="details">
<div class="col-xs-12 col-md-8 col-md-offset-2">
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Your Expenses!!!</div>

  <!-- Table -->
  <table class="table">
      <tr>
          <th>Date</th>
          <th>Description</th>
          <th>Amount</th>
      </tr>
      
      <tr>
          <% @expenses.each do |expense| %>
          <td><h4><%= expense.date %></h4></td>
          <td> <h4><%= expense.description %></h4></td>
          <td><h4><%= expense.amount %></h4></td>
         <td>
           
              <%= link_to "EDIT", edit_expense_path(expense), class: 'btn btn-sm btn-success'%>
             <%= link_to "DELETE", expense_path(expense), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you Sure???"}  %>
           </div>
           </td>
           </tr>
        <% end %>
  </table>
</div>


  
  <h2>Balance: <%= @expenses.where("amount > ?", 0).sum(:amount) %></h2>
  <h2>Debt:<%= @expenses.where("amount < ?", 0).sum(:amount) %></h2>
  <h2>Remaining:<%= @expenses.sum(:amount) %></h2>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <link href="https://fonts.googleapis.com/css?family=Aref+Ruqaa|Montserrat" rel="stylesheet">
  <title>Online-Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div id= 'wrap'>
  <%= render 'shared/nav' %>
  <%= render 'shared/flash_messages' %>
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"> <%= link_to "ONLINE-WALLET", root_path %></a>
      
    </div>
    
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to 'New Record', new_record_path %></li>
        <li><%= link_to 'About', about_path %></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/static_pages/about.html.erb
<h1>ABOUT</h1>
<p>Record your daily expenses and never lose track of your money!!!</p>
<H3>ONLINE-WALLET is always there for you...</H3>

app/views/static_pages/new_record.html.erb
<div class='form'>
<%= simple_form_for Expense.new do |f| %>
      <%= f.input :description %>
      <%= f.input :amount %>
      <%= f.input :date %>
      <%= f.submit class: 'btn btn-primary' %>
<% end %>
</div>